ENV: "debug"
HOST: "127.0.0.1"
PORT: "8000"
JWT_SECRET: ""
JWT_EXPIRE_TIME": 5
REDIS_HOST: "127.0.0.1"
REDIS_PORT: "6379"
REDIS_PASSWORD: ""
REDIS_DB: 0,
DB_HOST: "127.0.0.1"
DB_PORT: "27017"
DB_USER: ""
DB_PASSWORD: ""
DB_NAME: ""